import { Search } from "@/components/search";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ReportsProvider } from "@/provider/reports-provider";
import { ReportItem, ReportResponse } from "@/@types/report";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchInitialReports() {
  try {
    const response = await fetch("http://localhost:8080/api/reports", { cache: 'no-store' })
    const reports = await response.json() as (ReportResponse[] | undefined)

    if (!reports) return []

    return reports.map(it => ({
      ...it,
      created_at: new Date(it.created_at)
    })) as ReportItem[]
  } catch (error) {
    return []
  }

}

export default async function RootLayout({ children, }: { children: React.ReactNode; }) {
  const reports = await fetchInitialReports()

  return (
    <html lang="pt_BR">
      <ReportsProvider initialValue={reports}>
        <body className={inter.className}>
          <header className="flex h-20 gap-8 justify-evenly items-center p-4 pt-10 max-w-7xl mx-auto">
            <div>
              <Link href="/">
                <h1 className="font-bold text-3xl">Sentinel.</h1>
              </Link>
            </div>
            <Search />
          </header>
          {children}
        </body>
      </ReportsProvider>
    </html>
  );
}
